# workflow for running python tests
name: Test Python generation scripts

on:
  push:
    branches: ["main"]
    paths:
      - "generation/**"
      - ".github/workflows/generation-test-py.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generation
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
